import 'dart:convert';
import 'dart:io'; // Import for InternetAddress
import 'package:flutter/material.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import '../../../config/constants.dart';
import '../../../managers/game_manager.dart';
import '../models/game_models.dart'; // Use same GameResponse as GameManager

class SchoolSafetyQuizScreen extends StatefulWidget {
  final bool isResume;
  const SchoolSafetyQuizScreen({super.key, required this.isResume});

  @override
  State<SchoolSafetyQuizScreen> createState() => _SchoolSafetyQuizScreenState();
}

class _SchoolSafetyQuizScreenState extends State<SchoolSafetyQuizScreen> {
  late GameSession _session;
  final TextEditingController _textController = TextEditingController();
  final ScrollController _scrollController = ScrollController();

  @override
  void initState() {
    super.initState();
    // 1. Load the current session from the GameManager
    _session = GameManager().currentSession!;

    // 2. If it's a new game (not resuming) and no data exists, check net then start Gemini
    if (!widget.isResume && _session.currentScenarioData == null) {
      _checkNetworkAndStart();
    }
  }

  // --- NEW: Network Check Function ---
  Future<void> _checkNetworkAndStart() async {
    setState(() {
      _session.isLoading = true;
      _session.errorMessage = null;
    });

    try {
      final result = await InternetAddress.lookup('google.com');
      if (result.isNotEmpty && result[0].rawAddress.isNotEmpty) {
        // Network is good, start Gemini
        _initGemini();
      }
    } on SocketException catch (_) {
      // No Network
      setState(() {
        _session.isLoading = false;
        _session.errorMessage =
            '⚠️ No Internet Connection\n\nThis quiz is generated by AI and requires an active internet connection.\n\nPlease check your settings and try again.';
      });
    }
  }

  Future<void> _initGemini() async {
    if (apiKey.isEmpty) {
      setState(() {
        _session.errorMessage =
            'API KEY MISSING: Please add your key in constants.dart';
        _session.isLoading = false;
      });
      return;
    }

    try {
      final model = GenerativeModel(model: 'gemini-2.5-flash', apiKey: apiKey);

      // --- LANGUAGE SUPPORT LOGIC ---
      String langInstruction = '';
      if (_session.languageCode == 'hi') {
        langInstruction = '\nIMPORTANT: The user has selected HINDI. '
            'Generate all quiz content (questions, options, explanations, summary) in HINDI (Devanagari script). '
            "However, keep the JSON KEYS (like 'question_text', 'options', 'evaluation', 'next_question') strictly in English.";
      } else if (_session.languageCode == 'mr') {
        langInstruction = '\nIMPORTANT: The user has selected MARATHI. '
            'Generate all quiz content (questions, options, explanations, summary) in MARATHI. '
            "However, keep the JSON KEYS (like 'question_text', 'options', 'evaluation', 'next_question') strictly in English.";
      } else if (_session.languageCode == 'pa') {
        langInstruction = '\nIMPORTANT: The user has selected PUNJABI. '
            'Generate all quiz content (questions, options, explanations, summary) in PUNJABI (Gurmukhi script). '
            "However, keep the JSON KEYS (like 'question_text', 'options', 'evaluation', 'next_question') strictly in English.";
      }

      // Start chat with the Quiz Prompt + Language Instruction
      _session.chatSession = model.startChat(history: [
        Content.text(schoolSafetyQuizPrompt + langInstruction),
      ]);

      // Trigger the first question
      await _sendMessage('Start the School Safety Quiz. Question 1.',
          isSystemTrigger: true);
    } catch (e) {
      setState(() {
        _session.errorMessage =
            'Failed to connect to AI server. Please check your internet connection.';
        _session.isLoading = false;
      });
    }
  }

  Future<void> _handleUserResponse(String responseText) async {
    _textController.clear();
    FocusScope.of(context).unfocus();
    await _sendMessage(responseText);
  }

  Future<void> _sendMessage(String message,
      {bool isSystemTrigger = false}) async {
    setState(() {
      _session.isLoading = true;
      _session.errorMessage = null;
    });

    try {
      final response =
          await _session.chatSession!.sendMessage(Content.text(message));
      final rawText = response.text;
      if (rawText == null) throw Exception('Empty AI response');

      // Clean markdown formatting if present
      String jsonString = rawText
          .replaceAll(RegExp(r'^```json\s*'), '')
          .replaceAll(RegExp(r'\s*```$'), '');
      final decoded = jsonDecode(jsonString);
      final Map<String, dynamic> jsonData = (decoded is Map)
          ? decoded as Map<String, dynamic>
          : <String, dynamic>{};
      final gameResponse = GameResponse.fromJson(jsonData);

      setState(() {
        _session.isLoading = false;

        if (gameResponse.type == 'initial') {
          // Set the Static Header for the Quiz
          _session.persistentTitle = 'India School Safety Quiz';
          _session.persistentDescription =
              'Test your knowledge on disaster safety across India!';
          _session.currentScenarioData = gameResponse;
        } else if (gameResponse.type == 'turn') {
          // 1. Save the Turn to History
          _session.history.add(TurnHistoryItem(
            question: _session.currentScenarioData?.question ?? 'Question',
            userAnswer: message,
            evaluation: gameResponse.evaluation ?? 'Result',
            score: gameResponse.score ?? 0,
            explanation: gameResponse.explanation ?? '',
            source: gameResponse.sourceSummary ?? 'Safety Guidelines',
          ));

          // 2. Update Scores
          _session.totalScore += (gameResponse.score ?? 0);
          GameManager()
              .updateScores((gameResponse.score ?? 0), _session.totalScore);

          // 3. Prepare NEXT Question
          // Note: We update the title to show the Question Number
          _session.currentScenarioData = GameResponse(
            type: 'turn_scenario',
            scenarioTitle: "Question ${gameResponse.round ?? 'Next'}",
            scenarioDescription: 'Select the best option below.',
            question:
                gameResponse.nextQuestion, // Contains the new question text
            options: gameResponse.nextOptions, // Contains the new options
            round: gameResponse.round,
          );
        } else if (gameResponse.type == 'final') {
          // 1. Save Last Turn
          _session.history.add(TurnHistoryItem(
            question: _session.currentScenarioData?.question ?? 'Last Question',
            userAnswer: message,
            evaluation: gameResponse.evaluation ?? '',
            score: gameResponse.score ?? 0,
            explanation: gameResponse.explanation ?? '',
            source: gameResponse.sourceSummary ?? 'Safety Guidelines',
          ));

          // 2. Final Score Update
          _session.totalScore += (gameResponse.score ?? 0);
          GameManager()
              .updateScores((gameResponse.score ?? 0), _session.totalScore);

          // 3. End Game
          _session.isGameOver = true;
          _session.currentScenarioData = gameResponse;
        }
      });

      // Auto-scroll to bottom
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (_scrollController.hasClients) {
          _scrollController.animateTo(
            _scrollController.position.maxScrollExtent,
            duration: const Duration(milliseconds: 500),
            curve: Curves.easeOut,
          );
        }
      });
    } catch (e) {
      setState(() {
        _session.isLoading = false;
        _session.errorMessage = 'Connection Error: Please check your internet.';
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.blueGrey[50], // Distinct color for Quiz Mode
      appBar: AppBar(
        title: const Text('Safety Quiz 🇮🇳'),
        backgroundColor: Colors.indigo,
        foregroundColor: Colors.white,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
        actions: [
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            margin: const EdgeInsets.only(right: 16),
            decoration: BoxDecoration(
                color: Colors.white24, borderRadius: BorderRadius.circular(20)),
            child: Row(
              children: [
                const Icon(Icons.star, color: Colors.yellow, size: 18),
                const SizedBox(width: 4),
                Text('${_session.totalScore}',
                    style: const TextStyle(fontWeight: FontWeight.bold)),
              ],
            ),
          )
        ],
      ),
      body: _buildBody(),
    );
  }

  Widget _buildBody() {
    if (_session.errorMessage != null) {
      return Center(
          child: Padding(
        padding: const EdgeInsets.all(30.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.wifi_off, size: 60, color: Colors.red),
            const SizedBox(height: 20),
            Text(_session.errorMessage!,
                style: const TextStyle(color: Colors.black87, fontSize: 16),
                textAlign: TextAlign.center),
            const SizedBox(height: 30),
            ElevatedButton(
              onPressed: () {
                _session.errorMessage = null; // Clear error
                _checkNetworkAndStart(); // Retry
              },
              child: const Text('Retry Connection'),
            )
          ],
        ),
      ));
    }

    if (_session.isGameOver && _session.currentScenarioData != null) {
      return _buildFinalScreen(_session.currentScenarioData!);
    }

    if (_session.currentScenarioData == null && _session.isLoading) {
      return const Center(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          CircularProgressIndicator(),
          SizedBox(height: 20),
          Text('Loading Quiz...'),
        ],
      ));
    }

    return ListView(
      controller: _scrollController,
      padding: const EdgeInsets.all(16),
      children: [
        // 1. Persistent Header (e.g. "India School Safety Quiz")
        if (_session.persistentTitle != null) _buildPersistentHeader(),

        // 2. History
        if (_session.history.isNotEmpty)
          ..._session.history.map((turn) => _buildHistoryCard(turn)),

        const SizedBox(height: 20),

        // 3. Active Question
        if (_session.currentScenarioData != null)
          _buildActiveQuestionCard(_session.currentScenarioData!),

        const SizedBox(height: 20),

        // 4. Options (Buttons)
        if (!_session.isLoading &&
            _session.currentScenarioData?.options != null)
          ..._session.currentScenarioData!.options!.map((opt) => Padding(
                padding: const EdgeInsets.only(bottom: 12.0),
                child: SizedBox(
                  width: double.infinity,
                  child: ElevatedButton(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.white,
                      foregroundColor: Colors.black87,
                      elevation: 2,
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12)),
                      alignment: Alignment.centerLeft,
                      padding: const EdgeInsets.symmetric(
                          horizontal: 20, vertical: 16),
                    ),
                    onPressed: () => _handleUserResponse(opt),
                    child: Text(opt, style: const TextStyle(fontSize: 16)),
                  ),
                ),
              )),

        if (_session.isLoading)
          const Padding(
              padding: EdgeInsets.all(20.0),
              child: Center(child: CircularProgressIndicator())),

        const SizedBox(height: 40),
      ],
    );
  }

  // ... (Keep _buildPersistentHeader, _buildHistoryCard, _buildActiveQuestionCard, _buildFinalScreen as they were)

  Widget _buildPersistentHeader() {
    return Container(
      margin: const EdgeInsets.only(bottom: 20),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.indigo.shade50,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.indigo.shade100),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(children: [
            const Icon(Icons.school, color: Colors.indigo),
            const SizedBox(width: 10),
            Expanded(
                child: Text(_session.persistentTitle ?? '',
                    style: const TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                        color: Colors.indigo))),
          ]),
          const Divider(),
          Text(_session.persistentDescription ?? '',
              style: TextStyle(color: Colors.grey[800])),
        ],
      ),
    );
  }

  Widget _buildHistoryCard(TurnHistoryItem turn) {
    bool isCorrect = turn.evaluation.toLowerCase().contains('correct') &&
        !turn.evaluation.toLowerCase().contains('incorrect');
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border(
            left: BorderSide(
                color: isCorrect ? Colors.green : Colors.red, width: 4)),
        boxShadow: [
          BoxShadow(color: Colors.black.withValues(alpha: 0.05), blurRadius: 5)
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('Q: ${turn.question}',
              style: TextStyle(
                  fontWeight: FontWeight.bold,
                  color: Colors.grey[600],
                  fontSize: 12)),
          const SizedBox(height: 4),
          Text('You: ${turn.userAnswer}', style: const TextStyle(fontSize: 15)),
          const SizedBox(height: 12),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: isCorrect ? Colors.green.shade50 : Colors.red.shade50,
              borderRadius: BorderRadius.circular(8),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(children: [
                  Icon(isCorrect ? Icons.check_circle : Icons.cancel,
                      size: 16, color: isCorrect ? Colors.green : Colors.red),
                  const SizedBox(width: 6),
                  Text(turn.evaluation,
                      style: TextStyle(
                          fontWeight: FontWeight.bold,
                          color: isCorrect ? Colors.green : Colors.red)),
                  const Spacer(),
                  Text('+${turn.score}',
                      style: const TextStyle(fontWeight: FontWeight.bold)),
                ]),
                const SizedBox(height: 8),
                Text(turn.explanation, style: const TextStyle(fontSize: 14)),
                const SizedBox(height: 12),
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                      color: Colors.white.withValues(alpha: 0.6),
                      borderRadius: BorderRadius.circular(6),
                      border: Border.all(color: Colors.blueGrey.shade100)),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Icon(Icons.menu_book,
                          size: 14, color: Colors.indigo),
                      const SizedBox(width: 8),
                      Expanded(
                          child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text('OFFICIAL RESOURCE:',
                              style: TextStyle(
                                  fontSize: 10,
                                  fontWeight: FontWeight.bold,
                                  color: Colors.indigo)),
                          Text(turn.source,
                              style: const TextStyle(
                                  fontSize: 12,
                                  fontStyle: FontStyle.italic,
                                  color: Colors.blueGrey,
                                  height: 1.2)),
                        ],
                      )),
                    ],
                  ),
                )
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildActiveQuestionCard(GameResponse data) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(color: Colors.black.withValues(alpha: 0.1), blurRadius: 10)
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                    color: Colors.indigo.shade50,
                    borderRadius: BorderRadius.circular(8)),
                child: Text("QUESTION ${data.round ?? '?'}/10",
                    style: const TextStyle(
                        color: Colors.indigo,
                        fontWeight: FontWeight.bold,
                        fontSize: 12)),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Text(
            data.question ?? 'Loading next question...',
            style: const TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                color: Colors.black87),
          ),
        ],
      ),
    );
  }

  Widget _buildFinalScreen(GameResponse data) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        children: [
          const Icon(Icons.emoji_events, size: 80, color: Colors.indigo),
          const SizedBox(height: 20),
          const Text('Quiz Completed!',
              style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold)),
          const SizedBox(height: 10),
          Text('Total Score: ${data.finalScore}/100',
              style: const TextStyle(fontSize: 24, color: Colors.indigo)),
          if (data.performance != null)
            Text(data.performance!,
                style: const TextStyle(
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                    color: Colors.green)),
          const SizedBox(height: 30),
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
                color: Colors.white, borderRadius: BorderRadius.circular(20)),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Summary',
                    style:
                        TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                const Divider(),
                Text(data.preparednessSummary ?? 'No summary available.'),
                const SizedBox(height: 20),
                const Text('Recommended Actions',
                    style:
                        TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                const Divider(),
                Text(
                    data.recommendedActions ?? 'Review the safety guidelines.'),
              ],
            ),
          ),
          const SizedBox(height: 30),
          ElevatedButton(
            onPressed: () {
              GameManager().clearSession();
              Navigator.pop(context);
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.indigo,
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 15),
            ),
            child: const Text('Back to Menu'),
          )
        ],
      ),
    );
  }
}
